### ISSUE TITLE
Run cross-validation for BC = 1

### ISSUE THREAD

**Issue by rdgreene** [rdgreene/MNIST#1]
Box Constraint = [1]
Kernel Scale = [0.05 0.1 0.3 0.5 0.7 0.9]

**Comment by ginzsa-push** [comment]
Best option (and is the default value)
https://uk.mathworks.com/help/stats/fitcsvm.html#inputarg_BoxConstraint

**Comment by rdgreene** [comment]
Nice. So you'll run for all Kernel scale values for BC = 1?

Let me know when you have the scripts ready, I'll run them overnight!

**Comment by ginzsa-push** [comment]
Run to load data (if are not present in workspace)
svmLoadSaveDataSets.m
Open script
svmScalePerformance.m
Change line 6
boxContraint = 1;
load values line 21
save('svm_hog_linear_box1_scale_errors', 'trainCE', 'evalCE');

**Comment by ginzsa-push** [comment]
Ill be running this one

**Comment by rdgreene** [comment]
Early start!

So is that the last one we had to run???

**Comment by ginzsa-push** [comment]
Yes, that's it ,
With the best combination
I'll run the final create the confusion matrix

I'll try also to get the heat map of the results

San
