### ISSUE TITLE
Run cross-validation for BC = 2

### ISSUE THREAD

**Issue by rdgreene** [rdgreene/MNIST#2]
Box Constraint = [2]
Kernel Scale = [0.05 0.1 0.3 0.5 0.7 0.9]

**Comment by ginzsa-push** [comment]
Run to load data
svmLoadSaveDataSets.m
Open script
svmScalePerformance.m
Change line 6
boxContraint = 2;
load values line 21
save('svm_hog_linear_box2_scale_errors', 'trainCE', 'evalCE');

**Comment by ginzsa-push** [comment]
Ill do this one ..
