### ISSUE TITLE
Require rationale for SVM parameter choices

### ISSUE THREAD

**Issue by rdgreene** [rdgreene/MNIST#9]
@ginzsa-push 

Can you give me a brief description of why you chose the values you did to test for each hyperparameter (i.e. kernel function, kernel scale, box constraint)? Just something simple will do.

Also do you know what the default kernel scale & box constraint values are for each kernel function are in MATLAB?

R

**Comment by ginzsa-push** [comment]
Default box constraint is 1

average training & validation classification error for each different kernel choice

https://docs.google.com/spreadsheets/d/1mUU1vMiirQAV8Kl5FXwWZx1N4NczJZ82sAYPu-0KJfo/edit#gid=1312267635

Sheet 5
